#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=grader
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/grader
ensure_dir /local/grader
ensure_dir /local/grader/static
ensure_dir /local/grader/media
ensure_dir /local/grader/uploads
ensure_dir /local/grader/ex-meta

# Ensure group permissions
sock=/var/run/docker.sock
gid=$(stat -c '%g' $sock)
usermod -G $gid grader
